import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { AxiosError } from "axios";
import { beforeEach, describe, expect, it, vi } from "vitest";

const apiGet=vi.fn(),apiPost=vi.fn(),apiPatch=vi.fn();
vi.mock("@/lib/api",()=>({api:{get:(...args:unknown[])=>apiGet(...args),post:(...args:unknown[])=>apiPost(...args),patch:(...args:unknown[])=>apiPatch(...args)}}));
vi.mock("sonner",()=>({toast:{success:vi.fn(),error:vi.fn()}}));
vi.mock("@/components/ui/dropdown-menu",()=>({DropdownMenu:({children}:{children:React.ReactNode})=><>{children}</>,DropdownMenuTrigger:({children}:{children:React.ReactNode})=><>{children}</>,DropdownMenuContent:({children}:{children:React.ReactNode})=><div>{children}</div>,DropdownMenuItem:({children,onClick}:{children:React.ReactNode;onClick:()=>void})=><button onClick={onClick}>{children}</button>}));
import { IntelligentBriefingPanel } from "@/components/professional/IntelligentBriefingPanel";

const briefing={id:1,opportunity:7,problem:"Processo manual",objective:"Automatizar",target_audience:"Equipe",deliverables:["Painel"],functional_requirements:["Cadastrar lead"],non_functional_requirements:["Seguro"],integrations:["CRM"],data_requirements:[],infrastructure_requirements:[],constraints:[],dependencies:[],assumptions:[],scope_risks:["Escopo"],ambiguities:["Volume"],client_questions:["Qual volume?"],acceptance_criteria:["Lead salvo"],ai_provider:"test",ai_model:"model",updated_at:"2026-08-30T12:00:00Z"};
const notFound=()=>Object.assign(new AxiosError("not found"),{response:{status:404,data:{detail:"not found"}}});

describe("IntelligentBriefingPanel",()=>{
 beforeEach(()=>{vi.clearAllMocks();vi.spyOn(window,"confirm").mockReturnValue(true);});
 it("shows empty state, generates once and renders the executive reader",async()=>{apiGet.mockRejectedValue(notFound());apiPost.mockResolvedValue({data:briefing});render(<IntelligentBriefingPanel opportunityId={7}/>);const button=await screen.findByRole("button",{name:"Gerar briefing com IA"});fireEvent.click(button);expect((button as HTMLButtonElement).disabled).toBe(true);await screen.findByText(/Processo manual/);expect(apiPost).toHaveBeenCalledTimes(1);expect(screen.getByText("Resumo executivo")).toBeTruthy();expect(screen.getByText("Escopo e entrega")).toBeTruthy();expect(screen.getByText(/Qual volume/)).toBeTruthy();});
 it("shows a safe generation error and unlocks the button",async()=>{apiGet.mockRejectedValue(notFound());apiPost.mockRejectedValue(Object.assign(new AxiosError("secret"),{response:{status:503,data:{detail:"O provedor está indisponível."}}}));render(<IntelligentBriefingPanel opportunityId={7}/>);fireEvent.click(await screen.findByRole("button",{name:"Gerar briefing com IA"}));expect(await screen.findByText("O provedor está indisponível.")).toBeTruthy();expect((screen.getByRole("button",{name:"Gerar briefing com IA"}) as HTMLButtonElement).disabled).toBe(false);});
 it("edits and saves the human revision",async()=>{apiGet.mockResolvedValue({data:briefing});apiPatch.mockResolvedValue({data:{...briefing,problem:"Problema revisado"}});render(<IntelligentBriefingPanel opportunityId={7}/>);fireEvent.click(await screen.findByRole("button",{name:"Editar briefing"}));const problem=screen.getByDisplayValue("Processo manual");fireEvent.change(problem,{target:{value:"Problema revisado"}});fireEvent.click(screen.getByRole("button",{name:"Salvar briefing"}));await waitFor(()=>expect(apiPatch).toHaveBeenCalled());expect(apiPatch.mock.calls[0][1].problem).toBe("Problema revisado");expect(await screen.findByText(/Problema revisado/)).toBeTruthy();});
 it("requires confirmation before regenerating",async()=>{apiGet.mockResolvedValue({data:briefing});apiPost.mockResolvedValue({data:briefing});render(<IntelligentBriefingPanel opportunityId={7}/>);fireEvent.click(await screen.findByRole("button",{name:"Gerar novamente"}));expect(window.confirm).toHaveBeenCalled();await waitFor(()=>expect(apiPost).toHaveBeenCalledTimes(1));});
 it("opens the dedicated reader and exposes print and every export",async()=>{apiGet.mockResolvedValue({data:briefing});const open=vi.spyOn(window,"open").mockImplementation(()=>null);render(<IntelligentBriefingPanel opportunityId={7}/>);fireEvent.click(await screen.findByRole("button",{name:"Abrir briefing"}));expect(open).toHaveBeenCalledWith("/professional-studio/opportunities/7/briefing","_blank","noopener,noreferrer");expect(screen.getByRole("button",{name:"Imprimir"})).toBeTruthy();expect(screen.getByRole("button",{name:"Exportar"})).toBeTruthy();for(const format of ["PDF","DOCX","PPTX","MD","JSON"])expect(screen.getByRole("button",{name:format})).toBeTruthy();});
 it("shows a safe load error",async()=>{apiGet.mockRejectedValue(new Error("secret"));render(<IntelligentBriefingPanel opportunityId={7}/>);expect(await screen.findByText("Não foi possível carregar o briefing inteligente.")).toBeTruthy();});
});
