import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { LoaderCircle, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { api } from "@/lib/api";

type Attempt = { id: number; attempt_number: number; answer: string; feedback: string; outcome: string; identified_gap: string; next_step: string; ai_provider?: string; ai_model?: string; submitted_at: string };
type Activity = { id: number; activity_type_label: string; prompt: string; difficulty_label: string; competency_title: string; attempts: Attempt[]; ai_provider?: string; ai_model?: string; state: "GENERATED" | "ANSWERED" | "REVIEWED" };
type Provider = { id: string; label: string; available: boolean };
type ProviderResponse = { providers: Provider[]; selected_provider: string | null };
type ProviderSaveResponse = { provider: string };

export function SenseiLearningV1({ formationId, unitId, enabled }: { formationId: number | null; unitId: number; enabled: boolean }) {
  const client = useQueryClient(); const [response, setResponse] = useState(""); const [selectedProvider, setSelectedProvider] = useState(""); const providerQueryKey = ["sensei-learning-providers", formationId ?? "no-formation"];
  const queryKey = ["sensei-learning-activities", formationId ?? "no-formation", unitId];
  const providersQuery = useQuery({ queryKey: providerQueryKey, queryFn: async () => (await api.get<ProviderResponse>(`/api/library/sensei-formations/${formationId}/learning-providers/`)).data, enabled: Boolean(enabled && formationId), retry: false });
  useEffect(() => { if (providersQuery.data) setSelectedProvider(providersQuery.data.selected_provider ?? ""); }, [providersQuery.data]);
  const saveProvider = useMutation({ mutationFn: async (provider: string) => (await api.put<ProviderSaveResponse>(`/api/library/sensei-formations/${formationId}/learning-providers/`, { provider })).data, onSuccess: (data) => { setSelectedProvider(data.provider); client.setQueryData<ProviderResponse>(providerQueryKey, (current) => current ? { ...current, selected_provider: data.provider } : current); }, onError: () => toast.error("Não foi possível alterar o provider. A preferência anterior foi mantida.") });
  const query = useQuery({ queryKey, queryFn: async () => (await api.get<Activity[]>(`/api/library/sensei-units/${unitId}/learning-activities/`)).data, enabled, retry: false });
  const generate = useMutation({ mutationFn: async () => (await api.post<Activity>(`/api/library/sensei-units/${unitId}/learning-activities/`, {})).data, onSuccess: () => client.invalidateQueries({ queryKey }), onError: () => toast.error("O Sensei de Aprendizagem está temporariamente indisponível.") });
  const answer = useMutation({ mutationFn: async ({ id, text }: { id: number; text: string }) => (await api.post<Activity>(`/api/library/sensei-learning-activities/${id}/answer/`, { response: text })).data, onSuccess: () => { setResponse(""); client.invalidateQueries({ queryKey }); }, onError: () => toast.error("Não foi possível revisar agora. Sua atividade permaneceu intacta.") });
  if (!enabled) return null; const current = query.data?.[0];
  const attempts = current?.attempts ?? [];
  return <section aria-labelledby="sensei-learning-title" className="rounded-xl border border-primary/30 bg-primary/5 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id="sensei-learning-title" className="flex items-center gap-2 font-bold"><Sparkles className="h-4 w-4" />SENSEI DE APRENDIZAGEM</h3><p className="mt-1 text-xs text-muted-foreground">Prática guiada. Atividade concluída não é evidência validada nem demonstra competência.</p></div><Button disabled={generate.isPending} onClick={() => generate.mutate()}>{generate.isPending && <LoaderCircle className="animate-spin" />}{current ? "GERAR NOVO EXERCÍCIO" : "GERAR EXERCÍCIO"}</Button></div>
    <div className="mt-4 flex flex-wrap items-center gap-3"><label htmlFor="sensei-provider" className="text-sm font-medium">Provider de IA</label>{providersQuery.isLoading ? <span className="text-sm text-muted-foreground">Carregando providers...</span> : providersQuery.isError ? <span className="text-sm text-destructive">Não foi possível carregar os providers de IA.</span> : !providersQuery.data?.providers?.length ? <span className="text-sm text-muted-foreground">Nenhum provider de IA está disponível no momento.</span> : <select id="sensei-provider" aria-label="Provider de IA" value={selectedProvider} disabled={saveProvider.isPending} onChange={(event) => saveProvider.mutate(event.target.value)} className="h-9 min-w-40 rounded-md border border-input bg-background px-3 text-sm"><option value="" disabled>Selecione um provider</option>{providersQuery.data.providers.filter((provider) => provider.available).map((provider) => <option key={provider.id} value={provider.id}>{provider.label}</option>)}</select>}</div>
    {query.isLoading ? <p className="mt-4 text-sm text-muted-foreground">Carregando atividades...</p> : current ? <article className="mt-4 rounded-lg border bg-background p-4"><div className="flex flex-wrap gap-2"><Badge>{current.activity_type_label}</Badge><Badge variant="outline">Nível: {current.difficulty_label}</Badge><Badge variant="outline">{current.state}</Badge></div><p className="mt-2 text-xs text-muted-foreground">Competência: {current.competency_title}</p><p className="mt-3 whitespace-pre-wrap text-sm">{current.prompt}</p>
      {(current.ai_provider || current.ai_model) && <div className="mt-3 space-y-1 text-xs text-muted-foreground">{current.ai_provider && <p>Gerado por: {current.ai_provider}</p>}{current.ai_model && <p>Modelo: {current.ai_model}</p>}</div>}
      {attempts.length > 0 && <div className="mt-4 space-y-3" aria-label="Histórico de tentativas">{attempts.map((attempt) => <div key={attempt.id} className="space-y-2"><div className="rounded border p-3 text-sm"><b>TENTATIVA {attempt.attempt_number}</b><p className="mt-1 whitespace-pre-wrap">{attempt.answer}</p></div><div className="rounded border border-kaizen/30 p-3 text-sm"><b>FEEDBACK DO SENSEI</b><p className="mt-1 whitespace-pre-wrap">{attempt.feedback}</p><Badge className="mt-2" variant="outline">{attempt.outcome}</Badge>{attempt.identified_gap && <p className="mt-2 text-xs text-muted-foreground">Lacuna identificada: {attempt.identified_gap}</p>}{attempt.next_step && <p className="mt-1 text-xs text-muted-foreground">Próximo passo: {attempt.next_step}</p>}{(attempt.ai_provider || attempt.ai_model) && <div className="mt-2 space-y-1 text-xs text-muted-foreground">{attempt.ai_provider && <p>Avaliado por: {attempt.ai_provider}</p>}{attempt.ai_model && <p>Modelo: {attempt.ai_model}</p>}</div>}</div></div>)}</div>}
      <div className="mt-4 space-y-2"><h4 className="text-sm font-bold">{attempts.length ? "Tentar novamente" : "Sua primeira tentativa"}</h4><Textarea aria-label="Sua resposta ao exercício" value={response} onChange={(event) => setResponse(event.target.value)} placeholder="Explique seu raciocínio e registre sua tentativa" /><Button disabled={!response.trim() || answer.isPending} onClick={() => answer.mutate({ id: current.id, text: response })}>{attempts.length ? "TENTAR NOVAMENTE" : "ENVIAR RESPOSTA"}</Button></div>
    </article> : <p className="mt-4 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">Gere a primeira atividade contextualizada desta unidade.</p>}</section>;
}
