services:
  - type: web
    name: data-dojo-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: ./apps/api
    healthCheckPath: /health/
    preDeployCommand: python manage.py migrate --noinput
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: production
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_prod
      - key: ALLOWED_HOSTS
        value: "data-dojo-api.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: data-dojo-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: data-dojo-redis
          property: connectionString

  - type: worker
    name: data-dojo-worker
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: ./apps/api
    envVars:
      - key: SECRET_KEY
        fromService:
          type: web
          name: data-dojo-api
          envVarKey: SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: production
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_prod
      - key: DATABASE_URL
        fromDatabase:
          name: data-dojo-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: data-dojo-redis
          property: connectionString
    dockerCommand: celery -A config worker --loglevel=INFO

  - type: keyvalue
    name: data-dojo-redis
    plan: free
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: data-dojo-db
    plan: free
    region: oregon
