import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PrivateImage } from "@/components/library/PrivateImage";
import { errorMessage, uploadFile, type Page } from "@/components/library/library-api";

type Asset = { id: number; title: string; url: string; category: string; width: number; height: number; is_favorite: boolean; author: string; license: string; description: string; source_url: string };
const categories = ["BOOK_COVER", "BOOK_THUMBNAIL", "LOGO", "BACKGROUND", "OTHER"];
export default function LibraryMedia() {
  const client = useQueryClient(); const [page, setPage] = useState(1); const [category, setCategory] = useState(""); const [search, setSearch] = useState(""); const [favorite, setFavorite] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const query = useQuery({ queryKey: ["library-media", page, category, search, favorite], queryFn: async () => (await api.get<Page<Asset>>("/api/library/media/", { params: { page, category, search, favorite } })).data });
  async function act(action: () => Promise<unknown>) { setBusy(true); setError(""); try { await action(); await client.invalidateQueries({ queryKey: ["library-media"] }); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <main className="mx-auto min-h-screen max-w-6xl space-y-6 p-6"><Link to="/library/" className="text-primary">← Biblioteca</Link><h1 className="font-display text-3xl font-bold">Banco de imagens</h1><p className="text-muted-foreground">Capas, miniaturas e imagens institucionais.</p><div className="flex flex-wrap gap-4"><Input className="max-w-xs" aria-label="Buscar imagens" placeholder="Buscar imagens" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /><select aria-label="Categoria da imagem" className="rounded border bg-background p-2" value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="">Todas as categorias</option>{categories.map(c => <option key={c}>{c}</option>)}</select><label><input type="checkbox" checked={favorite} onChange={e => { setFavorite(e.target.checked); setPage(1); }} /> Favoritas</label><label className="cursor-pointer rounded border p-2">Adicionar imagem<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} className="sr-only" onChange={e => { const file = e.target.files?.[0]; if (file) void act(() => uploadFile("/api/library/media/", file, { category: category || "OTHER" })); e.target.value = ""; }} /></label></div>{(error || query.isError) && <p role="alert">{error || errorMessage(query.error)}</p>}{query.isLoading && <p>Carregando imagens…</p>}<div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">{query.data?.results.map(asset => <article key={asset.id} className="space-y-3 rounded-xl border p-4"><PrivateImage url={asset.url} title={asset.title} className="h-48 w-full object-contain" /><h2 className="font-bold">{asset.title}</h2><p className="text-xs">{asset.category} · {asset.width} × {asset.height}</p><p className="text-sm">{asset.author} {asset.license && `· ${asset.license}`}</p><Button disabled={busy} variant="outline" onClick={() => void act(() => api.patch(`/api/library/media/${asset.id}/`, { is_favorite: !asset.is_favorite }))}>{asset.is_favorite ? "★ Favorita" : "☆ Favoritar"}</Button><Button disabled={busy} variant="ghost" onClick={() => { const title = window.prompt("Título", asset.title); if (!title) return; const author = window.prompt("Autor", asset.author); if (author === null) return; const license = window.prompt("Licença", asset.license); if (license !== null) void act(() => api.patch(`/api/library/media/${asset.id}/`, { title, author, license })); }}>Editar metadados</Button></article>)}</div>{query.data?.count === 0 && <p>Nenhuma imagem encontrada.</p>}<nav className="flex items-center justify-center gap-4"><Button disabled={!query.data?.previous} onClick={() => setPage(page - 1)}>Anterior</Button><span>Página {page}</span><Button disabled={!query.data?.next} onClick={() => setPage(page + 1)}>Próxima</Button></nav></main>;
}
