import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { AxiosError } from "axios";
import { BriefcaseBusiness, Download, Eye, FileText, LoaderCircle, Pencil, Plus, Printer, Trash2 } from "lucide-react";
import { toast, Toaster } from "sonner";

import { DojoHeader } from "@/components/DojoHeader";
import { IntelligentBriefingPanel } from "@/components/professional/IntelligentBriefingPanel";
import { MoneyWorkflowPanel } from "@/components/professional/MoneyWorkflowPanel";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { api } from "@/lib/api";

export type Modality = { id: number; name: string; slug: string; domain: string; domain_label: string; is_active: boolean; sort_order: number };
type Opportunity = { id:number; title:string; description:string; source:string; source_url:string; client_name:string; client_reference:string; budget_min:string|null; budget_max:string|null; currency:string; deadline:string|null; proposal_deadline:string|null; status:string; notes:string; modalities:Modality[]; created_at:string; updated_at:string };
type Page<T> = { count:number; next:string|null; previous:string|null; results:T[] };
type Form = { title:string; description:string; source:string; source_url:string; client_name:string; client_reference:string; budget_min:string; budget_max:string; currency:string; deadline:string; proposal_deadline:string; status:string; modality_ids:number[]; notes:string };
type ProposalVersion="SHORT"|"CONSULTATIVE"|"TECHNICAL";
type PersistedProposal={id:number;version:ProposalVersion;status:"DRAFT"|"APPROVED";greeting:string;understanding:string;approach:string;deliverables:string[];deadline:string;suggested_price:string|null;currency:string;essential_questions:string[];differentiators:string[];closing:string};

const sources:Record<string,string>={"99FREELAS":"99Freelas",WORKANA:"Workana",UPWORK:"Upwork",DIRECT_CLIENT:"Cliente direto",REFERRAL:"Indicação",PROSPECTING:"Prospecção",AGENCIA_3DS:"Agência 3DS",OWN_PROJECT:"Projeto próprio",OTHER:"Outra"};
const statuses:Record<string,string>={NEW:"Nova",ANALYZING:"Em análise",INTERESTED:"Interessado",NEGOTIATING:"Negociando",PROPOSAL_SENT:"Proposta enviada",WON:"Ganha",LOST:"Perdida",REJECTED:"Rejeitada",ARCHIVED:"Arquivada"};
const empty:Form={title:"",description:"",source:"DIRECT_CLIENT",source_url:"",client_name:"",client_reference:"",budget_min:"",budget_max:"",currency:"BRL",deadline:"",proposal_deadline:"",status:"NEW",modality_ids:[],notes:""};
const asForm=(o:Opportunity):Form=>({...o,budget_min:o.budget_min??"",budget_max:o.budget_max??"",deadline:o.deadline??"",proposal_deadline:o.proposal_deadline??"",modality_ids:o.modalities.map(item=>item.id)});

function message(error:unknown){if(!(error instanceof AxiosError))return"Não foi possível concluir a operação.";const data=error.response?.data as Record<string,unknown>|undefined;const first=data&&Object.values(data)[0];return Array.isArray(first)?String(first[0]):typeof first==="string"?first:"Revise os dados informados.";}

export function ModalityPicker({catalog,selected,onChange,disabled=false}:{catalog:Modality[];selected:number[];onChange:(ids:number[])=>void;disabled?:boolean}){
 const domains=[...new Set(catalog.map(item=>item.domain))];
 const toggle=(id:number)=>onChange(selected.includes(id)?selected.filter(item=>item!==id):[...selected,id]);
 if(!catalog.length)return <p className="rounded-md border border-dashed p-3 text-sm text-muted-foreground">Nenhuma modalidade disponível.</p>;
 return <div className="max-h-56 space-y-3 overflow-y-auto rounded-lg border p-3">{domains.map(domain=><fieldset key={domain}><legend className="mb-2 text-xs font-bold uppercase tracking-wide text-muted-foreground">{catalog.find(item=>item.domain===domain)?.domain_label}</legend><div className="flex flex-wrap gap-2">{catalog.filter(item=>item.domain===domain).map(item=><button key={item.id} type="button" disabled={disabled} aria-pressed={selected.includes(item.id)} onClick={()=>toggle(item.id)} className={`rounded-full border px-3 py-1.5 text-xs font-medium transition ${selected.includes(item.id)?"border-kaizen bg-kaizen/15 text-kaizen":"border-border text-muted-foreground hover:text-foreground"}`}>{selected.includes(item.id)?"✓ ":""}{item.name}</button>)}</div></fieldset>)}</div>;
}

export default function ProfessionalStudio(){
 const [items,setItems]=useState<Opportunity[]>([]),[page,setPage]=useState(1),[meta,setMeta]=useState<Page<Opportunity>|null>(null);
 const [catalog,setCatalog]=useState<Modality[]>([]),[catalogError,setCatalogError]=useState("");
 const [filter,setFilter]=useState(""),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 const [formOpen,setFormOpen]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState<Form>(empty);
 const [viewing,setViewing]=useState<Opportunity|null>(null),[editing,setEditing]=useState<Opportunity|null>(null),[deleting,setDeleting]=useState<Opportunity|null>(null);

 async function load(target=page,modality=filter){setLoading(true);setLoadError("");try{const response=await api.get<Page<Opportunity>>("/api/professional/opportunities/",{params:{page:target,modality:modality||undefined}});setItems(response.data.results);setMeta(response.data);setPage(target);}catch{setLoadError("Não foi possível carregar suas oportunidades.");}finally{setLoading(false);}}
 async function loadCatalog(){setCatalogError("");try{const response=await api.get<Modality[]>("/api/professional/modalities/");setCatalog(response.data);}catch{setCatalogError("Não foi possível carregar as modalidades.");}}
 useEffect(()=>{void Promise.all([load(1,""),loadCatalog()]);},[]);
 const update=(field:keyof Form,value:Form[keyof Form])=>setForm(current=>({...current,[field]:value}));
 function create(){setEditing(null);setForm(empty);setFormOpen(true);} function edit(o:Opportunity){setEditing(o);setForm(asForm(o));setFormOpen(true);}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);const payload={...form,budget_min:form.budget_min||null,budget_max:form.budget_max||null,deadline:form.deadline||null,proposal_deadline:form.proposal_deadline||null,currency:form.currency.toUpperCase()};try{editing?await api.patch(`/api/professional/opportunities/${editing.id}/`,payload):await api.post("/api/professional/opportunities/",payload);toast.success(editing?"Oportunidade atualizada.":"Oportunidade criada.");setFormOpen(false);await load(editing?page:1);}catch(error){toast.error(message(error));}finally{setSaving(false);}}
 async function remove(){if(!deleting)return;try{await api.delete(`/api/professional/opportunities/${deleting.id}/`);toast.success("Oportunidade excluída.");setDeleting(null);await load(items.length===1&&page>1?page-1:page);}catch(error){toast.error(message(error));}}
 function applyFilter(value:string){setFilter(value);void load(1,value);}

 return <div className="min-h-screen bg-background text-foreground"><Toaster position="top-right" richColors/><DojoHeader/><main className="mx-auto max-w-7xl px-4 py-8 sm:py-12"><header className="flex flex-col gap-5 border-b pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-kaizen">Ecossistema 3DS</p><h1 className="mt-2 font-display text-3xl font-black sm:text-4xl">Professional Project Studio</h1><p className="mt-2 text-muted-foreground">Transforme oportunidades reais em projetos planejados, executáveis e rentáveis.</p></div><Button onClick={create}><Plus/>Nova oportunidade</Button></header>
 <div className="mt-6 flex justify-end"><select aria-label="Filtrar por modalidade" className="h-10 max-w-xs rounded-md border border-input bg-background px-3 text-sm" value={filter} disabled={!!catalogError} onChange={event=>applyFilter(event.target.value)}><option value="">Todas as modalidades</option>{catalog.map(item=><option key={item.id} value={item.slug}>{item.name}</option>)}</select></div>
 <section className="mt-4" aria-live="polite">{loading?<State><LoaderCircle className="animate-spin"/>Carregando oportunidades...</State>:loadError?<State><p className="text-destructive">{loadError}</p><Button variant="outline" onClick={()=>void load()}>Tentar novamente</Button></State>:items.length===0?<State><BriefcaseBusiness className="h-12 w-12 text-kaizen"/><h2 className="text-xl font-bold">{filter?"Nenhuma oportunidade nesta modalidade":"Sua central está pronta"}</h2><p className="max-w-md text-sm text-muted-foreground">{filter?"Escolha outra modalidade ou limpe o filtro.":"Registre a primeira oportunidade para acompanhar briefing, orçamento e prazos."}</p>{!filter&&<Button onClick={create}><Plus/>Nova oportunidade</Button>}</State>:<div className="space-y-4">{items.map(o=><Card key={o.id}><CardContent className="grid gap-5 p-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold">{o.title}</h2><Badge variant="outline">{sources[o.source]??o.source}</Badge><Badge>{statuses[o.status]??o.status}</Badge></div><ModalityChips modalities={o.modalities}/><div className="mt-3 grid gap-2 text-sm text-muted-foreground sm:grid-cols-3"><p><b className="text-foreground">Orçamento:</b> {budget(o)}</p><p><b className="text-foreground">Prazo:</b> {date(o.deadline)}</p><p><b className="text-foreground">Criada:</b> {date(o.created_at)}</p></div></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setViewing(o)}><Eye/>Visualizar</Button><Button size="sm" variant="outline" onClick={()=>edit(o)}><Pencil/>Editar</Button><Button size="sm" variant="destructive" onClick={()=>setDeleting(o)}><Trash2/>Excluir</Button></div></CardContent></Card>)}{meta&&meta.count>10&&<div className="flex justify-end gap-3"><Button variant="outline" disabled={!meta.previous} onClick={()=>void load(page-1)}>Anterior</Button><span className="py-2 text-sm">Página {page}</span><Button variant="outline" disabled={!meta.next} onClick={()=>void load(page+1)}>Próxima</Button></div>}</div>}</section></main>
 <Dialog open={formOpen} onOpenChange={open=>!saving&&setFormOpen(open)}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Editar oportunidade":"Nova oportunidade"}</DialogTitle><DialogDescription>Registre os dados disponíveis agora. Você poderá complementar depois.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Título *" wide><Input required maxLength={200} value={form.title} onChange={e=>update("title",e.target.value)}/></Field><Field label="Origem *"><Select value={form.source} options={sources} onChange={v=>update("source",v)}/></Field><Field label="Status"><Select value={form.status} options={statuses} onChange={v=>update("status",v)}/></Field><Field label="URL da oportunidade"><Input type="url" value={form.source_url} onChange={e=>update("source_url",e.target.value)} placeholder="https://"/></Field><Field label="Cliente"><Input value={form.client_name} onChange={e=>update("client_name",e.target.value)}/></Field><Field label="Descrição / briefing bruto *" wide><Textarea required rows={5} value={form.description} onChange={e=>update("description",e.target.value)}/></Field><Field label="Modalidades / Nichos" wide>{catalogError?<div className="rounded-md border border-destructive/40 p-3 text-sm text-destructive"><p>{catalogError}</p><Button className="mt-2" size="sm" type="button" variant="outline" onClick={()=>void loadCatalog()}>Tentar novamente</Button></div>:<ModalityPicker catalog={catalog} selected={form.modality_ids} onChange={ids=>update("modality_ids",ids)} disabled={saving}/>}</Field><Field label="Orçamento mínimo"><Input type="number" min="0" step=".01" value={form.budget_min} onChange={e=>update("budget_min",e.target.value)}/></Field><Field label="Orçamento máximo"><Input type="number" min="0" step=".01" value={form.budget_max} onChange={e=>update("budget_max",e.target.value)}/></Field><Field label="Moeda *"><Input required minLength={3} maxLength={3} value={form.currency} onChange={e=>update("currency",e.target.value.toUpperCase())}/></Field><Field label="Prazo"><Input type="date" value={form.deadline} onChange={e=>update("deadline",e.target.value)}/></Field><Field label="Data limite da proposta"><Input type="date" value={form.proposal_deadline} onChange={e=>update("proposal_deadline",e.target.value)}/></Field><Field label="Referência do cliente"><Input value={form.client_reference} onChange={e=>update("client_reference",e.target.value)}/></Field><Field label="Observações" wide><Textarea rows={3} value={form.notes} onChange={e=>update("notes",e.target.value)}/></Field><DialogFooter className="sm:col-span-2"><Button type="button" variant="outline" disabled={saving} onClick={()=>setFormOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving||!!catalogError}>{saving&&<LoaderCircle className="animate-spin"/>}{saving?"Salvando...":"Salvar oportunidade"}</Button></DialogFooter></form></DialogContent></Dialog>
<Dialog open={!!viewing} onOpenChange={open=>!open&&setViewing(null)}><DialogContent className="max-h-[92vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{viewing?.title}</DialogTitle><DialogDescription>{viewing&&`${sources[viewing.source]} · ${statuses[viewing.status]}`}</DialogDescription></DialogHeader>{viewing&&<div className="grid gap-4 text-sm sm:grid-cols-2"><Detail label="Cliente" value={viewing.client_name||"Não informado"}/><Detail label="Orçamento" value={budget(viewing)}/><Detail label="Prazo" value={date(viewing.deadline)}/><Detail label="Limite da proposta" value={date(viewing.proposal_deadline)}/><div className="sm:col-span-2"><b>Modalidades</b><div className="mt-2">{viewing.modalities.length?<div className="flex flex-wrap gap-2">{viewing.modalities.map(item=><Badge key={item.id} variant="outline">{item.name}</Badge>)}</div>:<p className="text-muted-foreground">Nenhuma modalidade selecionada.</p>}</div></div><Detail label="Descrição" value={viewing.description} wide/><Detail label="Observações" value={viewing.notes||"Sem observações"} wide/>{viewing.source_url&&<a className="text-kaizen underline sm:col-span-2" href={viewing.source_url} target="_blank" rel="noreferrer">Abrir oportunidade original ↗</a>}<MoneyWorkflowPanel opportunityId={viewing.id}/><ProposalExportPanel opportunity={viewing}/><IntelligentBriefingPanel opportunityId={viewing.id}/></div>}<DialogFooter><Button variant="outline" onClick={()=>setViewing(null)}>Fechar</Button>{viewing&&<Button onClick={()=>{const o=viewing;setViewing(null);edit(o);}}>Editar oportunidade</Button>}</DialogFooter></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>!open&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir oportunidade?</AlertDialogTitle><AlertDialogDescription>“{deleting?.title}” será removida permanentemente.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground" onClick={()=>void remove()}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}

function ModalityChips({modalities}:{modalities:Modality[]}){if(!modalities.length)return <p className="mt-3 text-xs text-muted-foreground">Sem modalidades</p>;const visible=modalities.slice(0,3);return <div className="mt-3 flex flex-wrap gap-1.5">{visible.map(item=><Badge key={item.id} variant="secondary">{item.name}</Badge>)}{modalities.length>3&&<Badge variant="secondary">+{modalities.length-3}</Badge>}</div>}
function State({children}:{children:ReactNode}){return <Card><CardContent className="flex min-h-56 flex-col items-center justify-center gap-4 text-center">{children}</CardContent></Card>}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:ReactNode}){return <div className={`space-y-2 ${wide?"sm:col-span-2":""}`}><Label>{label}</Label>{children}</div>}
function Select({value,options,onChange}:{value:string;options:Record<string,string>;onChange:(v:string)=>void}){return <select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function Detail({label,value,wide=false}:{label:string;value:string;wide?:boolean}){return <div className={wide?"sm:col-span-2":""}><b>{label}</b><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{value}</p></div>}
const proposalVersions:Record<ProposalVersion,string>={SHORT:"Curta",CONSULTATIVE:"Consultiva",TECHNICAL:"Técnica"};
export function ProposalExportPanel({opportunity}:{opportunity:Opportunity}){
 const [version,setVersion]=useState<ProposalVersion>("CONSULTATIVE"),[proposal,setProposal]=useState<PersistedProposal|null>(null),[loading,setLoading]=useState(true),[exporting,setExporting]=useState("");
 async function load(selected:ProposalVersion){setLoading(true);try{const response=await api.get<PersistedProposal>(`/api/professional/opportunities/${opportunity.id}/proposal/`,{params:{version:selected}});setProposal(response.data);}catch(error){if(error instanceof AxiosError&&error.response?.status===404)setProposal(null);else toast.error("Não foi possível verificar a proposta persistida.");}finally{setLoading(false);}}
 useEffect(()=>{void load(version);},[opportunity.id,version]);
 async function download(format:"pdf"|"docx"){setExporting(format);try{const response=await api.get(`/api/professional/opportunities/${opportunity.id}/proposal/export/${format}/`,{params:{version},responseType:"blob"});const url=URL.createObjectURL(response.data);const link=document.createElement("a");link.href=url;link.download=`proposta-${opportunity.title}-${version.toLowerCase()}.${format}`;link.click();URL.revokeObjectURL(url);}catch(error){toast.error(safeProposalError(error));}finally{setExporting("");}}
 function print(){if(!proposal)return;const popup=window.open("","_blank");if(!popup){toast.error("O navegador bloqueou a janela de impressão.");return;}popup.opener=null;const sections:[string,string|string[]][]=[["Saudação",proposal.greeting],["Entendimento da necessidade",proposal.understanding],["Abordagem proposta",proposal.approach],["Entregáveis",proposal.deliverables],["Prazo",proposal.deadline],["Perguntas essenciais",proposal.essential_questions],["Diferenciais",proposal.differentiators],["Encerramento",proposal.closing]];const investment=proposal.suggested_price?`<p><strong>Investimento:</strong> ${escapeHtml(proposal.currency)} ${escapeHtml(proposal.suggested_price)}</p>`:"";const body=sections.filter(([,value])=>Array.isArray(value)?value.length:Boolean(value)).map(([title,value])=>`<section><h2>${escapeHtml(title)}</h2>${Array.isArray(value)?`<ul>${value.map(item=>`<li>${escapeHtml(item)}</li>`).join("")}</ul>`:`<p>${escapeHtml(value)}</p>`}</section>`).join("");popup.document.write(`<!doctype html><html lang="pt-BR"><head><title>Proposta Comercial - ${escapeHtml(opportunity.title)}</title><style>@page{margin:18mm}body{font:11pt Arial,sans-serif;color:#1c1c1c;line-height:1.5;max-width:780px;margin:auto}header{border-bottom:3px solid #0057b8;margin-bottom:28px;padding-bottom:18px}h1{margin:4px 0;font-size:26pt}h2{color:#0057b8;font-size:15pt;margin:22px 0 7px}small{color:#667085}li{margin-bottom:5px}@media print{body{max-width:none}}</style></head><body><header><strong>3DS Marketing Digital &amp; Tecnologia</strong><h1>Proposta Comercial</h1><p>${escapeHtml(opportunity.title)}</p>${opportunity.client_name?`<p><strong>Cliente:</strong> ${escapeHtml(opportunity.client_name)}</p>`:""}<small>Versão ${escapeHtml(proposalVersions[version])}</small>${investment}</header>${body}</body></html>`);popup.document.close();popup.focus();popup.print();}
 const disabled=loading||!proposal||!!exporting;
 return <section className="space-y-3 border-t pt-5 sm:col-span-2"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="flex items-center gap-2 text-lg font-bold"><FileText className="h-5 w-5"/>Exportação da proposta</h3><p className="text-xs text-muted-foreground">Imprima ou baixe a versão persistida, sem gerar novo conteúdo.</p></div><label className="text-xs text-muted-foreground">Versão<select aria-label="Versão para exportação" className="ml-2 rounded border bg-background px-2 py-1" value={version} onChange={event=>setVersion(event.target.value as ProposalVersion)}>{Object.entries(proposalVersions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{!loading&&!proposal&&<p className="rounded-md border border-dashed p-3 text-sm text-muted-foreground">Ainda não existe proposta persistida para esta versão.</p>}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={disabled} onClick={print}><Printer/>Imprimir</Button><Button type="button" variant="outline" disabled={disabled} onClick={()=>void download("pdf")}>{exporting==="pdf"?<LoaderCircle className="animate-spin"/>:<Download/>}Exportar PDF</Button><Button type="button" variant="outline" disabled={disabled} onClick={()=>void download("docx")}>{exporting==="docx"?<LoaderCircle className="animate-spin"/>:<Download/>}Exportar DOCX</Button></div></section>;
}
function safeProposalError(error:unknown){return error instanceof AxiosError&&typeof error.response?.data?.detail==="string"?error.response.data.detail:"Não foi possível exportar a proposta."}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[character]!));}
function date(value:string|null){if(!value)return"Não informado";return new Date(value.length===10?`${value}T12:00:00`:value).toLocaleDateString("pt-BR")}
function budget(o:Opportunity){if(!o.budget_min&&!o.budget_max)return"Não informado";const f=(v:string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:o.currency}).format(Number(v));return o.budget_min&&o.budget_max?`${f(o.budget_min)} – ${f(o.budget_max)}`:f((o.budget_min??o.budget_max)!)}
