# Generated by Django 6.0.6 on 2026-07-16 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumtopic",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_forum_topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
