# Generated by Django 6.0.6 on 2026-08-30 03:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField()),
                ('submitted_answer', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('attempt_number', models.PositiveIntegerField()),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('feedback', models.JSONField(default=dict)),
                ('evaluation_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='core.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempt_number'],
                'indexes': [models.Index(fields=['user', 'exercise', '-created_at'], name='attempt_user_exercise_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise', 'attempt_number'), name='unique_user_exercise_attempt_number'), models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_user_attempt_idempotency_key')],
            },
        ),
    ]
