# Generated by Django 6.0.6 on 2026-09-01 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_courseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Não iniciada'), ('in_progress', 'Em andamento'), ('completed', 'Concluída')], db_index=True, default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='core.courseprogress')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress', to='core.lesson')),
            ],
            options={
                'ordering': ['-last_activity_at', 'lesson_id'],
                'constraints': [models.UniqueConstraint(fields=('course_progress', 'lesson'), name='unique_course_progress_lesson')],
            },
        ),
    ]
