# Generated by Django 6.0.6 on 2026-09-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='academic_state',
            field=models.CharField(choices=[('not_started', 'Não iniciado'), ('in_progress', 'Em andamento'), ('completed', 'Concluído')], db_index=True, default='not_started', max_length=20),
        ),
    ]
