/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfessionalStudioRouteImport } from './routes/professional-studio'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContentStudioRouteImport } from './routes/content-studio'
import { Route as ConhecaSenseyRouteImport } from './routes/conheca-sensey'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AiSalesRouteImport } from './routes/ai-sales'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryMediaRouteImport } from './routes/library.media'
import { Route as ProfessionalStudioOpportunitiesOpportunityIdBriefingRouteImport } from './routes/professional-studio.opportunities.$opportunityId.briefing'
import { Route as LibraryBooksBookIdReadRouteImport } from './routes/library.books.$bookId.read'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalStudioRoute = ProfessionalStudioRouteImport.update({
  id: '/professional-studio',
  path: '/professional-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentStudioRoute = ContentStudioRouteImport.update({
  id: '/content-studio',
  path: '/content-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecaSenseyRoute = ConhecaSenseyRouteImport.update({
  id: '/conheca-sensey',
  path: '/conheca-sensey',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSalesRoute = AiSalesRouteImport.update({
  id: '/ai-sales',
  path: '/ai-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMediaRoute = LibraryMediaRouteImport.update({
  id: '/library/media',
  path: '/library/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalStudioOpportunitiesOpportunityIdBriefingRoute =
  ProfessionalStudioOpportunitiesOpportunityIdBriefingRouteImport.update({
    id: '/opportunities/$opportunityId/briefing',
    path: '/opportunities/$opportunityId/briefing',
    getParentRoute: () => ProfessionalStudioRoute,
  } as any)
const LibraryBooksBookIdReadRoute = LibraryBooksBookIdReadRouteImport.update({
  id: '/library/books/$bookId/read',
  path: '/library/books/$bookId/read',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-sales': typeof AiSalesRoute
  '/community': typeof CommunityRoute
  '/conheca-sensey': typeof ConhecaSenseyRoute
  '/content-studio': typeof ContentStudioRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/professional-studio': typeof ProfessionalStudioRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRoute
  '/workspace': typeof WorkspaceRoute
  '/library/media': typeof LibraryMediaRoute
  '/library/': typeof LibraryIndexRoute
  '/library/books/$bookId/read': typeof LibraryBooksBookIdReadRoute
  '/professional-studio/opportunities/$opportunityId/briefing': typeof ProfessionalStudioOpportunitiesOpportunityIdBriefingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-sales': typeof AiSalesRoute
  '/community': typeof CommunityRoute
  '/conheca-sensey': typeof ConhecaSenseyRoute
  '/content-studio': typeof ContentStudioRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/professional-studio': typeof ProfessionalStudioRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRoute
  '/workspace': typeof WorkspaceRoute
  '/library/media': typeof LibraryMediaRoute
  '/library': typeof LibraryIndexRoute
  '/library/books/$bookId/read': typeof LibraryBooksBookIdReadRoute
  '/professional-studio/opportunities/$opportunityId/briefing': typeof ProfessionalStudioOpportunitiesOpportunityIdBriefingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-sales': typeof AiSalesRoute
  '/community': typeof CommunityRoute
  '/conheca-sensey': typeof ConhecaSenseyRoute
  '/content-studio': typeof ContentStudioRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/professional-studio': typeof ProfessionalStudioRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRoute
  '/workspace': typeof WorkspaceRoute
  '/library/media': typeof LibraryMediaRoute
  '/library/': typeof LibraryIndexRoute
  '/library/books/$bookId/read': typeof LibraryBooksBookIdReadRoute
  '/professional-studio/opportunities/$opportunityId/briefing': typeof ProfessionalStudioOpportunitiesOpportunityIdBriefingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/ai-sales'
    | '/community'
    | '/conheca-sensey'
    | '/content-studio'
    | '/dashboard'
    | '/login'
    | '/portfolio'
    | '/professional-studio'
    | '/profile'
    | '/recuperar-senha'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/workspace'
    | '/library/media'
    | '/library/'
    | '/library/books/$bookId/read'
    | '/professional-studio/opportunities/$opportunityId/briefing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/ai-sales'
    | '/community'
    | '/conheca-sensey'
    | '/content-studio'
    | '/dashboard'
    | '/login'
    | '/portfolio'
    | '/professional-studio'
    | '/profile'
    | '/recuperar-senha'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/workspace'
    | '/library/media'
    | '/library'
    | '/library/books/$bookId/read'
    | '/professional-studio/opportunities/$opportunityId/briefing'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/ai-sales'
    | '/community'
    | '/conheca-sensey'
    | '/content-studio'
    | '/dashboard'
    | '/login'
    | '/portfolio'
    | '/professional-studio'
    | '/profile'
    | '/recuperar-senha'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/workspace'
    | '/library/media'
    | '/library/'
    | '/library/books/$bookId/read'
    | '/professional-studio/opportunities/$opportunityId/briefing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AiSalesRoute: typeof AiSalesRoute
  CommunityRoute: typeof CommunityRoute
  ConhecaSenseyRoute: typeof ConhecaSenseyRoute
  ContentStudioRoute: typeof ContentStudioRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfessionalStudioRoute: typeof ProfessionalStudioRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoreRoute: typeof StoreRoute
  WorkspaceRoute: typeof WorkspaceRoute
  LibraryMediaRoute: typeof LibraryMediaRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryBooksBookIdReadRoute: typeof LibraryBooksBookIdReadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-studio': {
      id: '/professional-studio'
      path: '/professional-studio'
      fullPath: '/professional-studio'
      preLoaderRoute: typeof ProfessionalStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-studio': {
      id: '/content-studio'
      path: '/content-studio'
      fullPath: '/content-studio'
      preLoaderRoute: typeof ContentStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conheca-sensey': {
      id: '/conheca-sensey'
      path: '/conheca-sensey'
      fullPath: '/conheca-sensey'
      preLoaderRoute: typeof ConhecaSenseyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-sales': {
      id: '/ai-sales'
      path: '/ai-sales'
      fullPath: '/ai-sales'
      preLoaderRoute: typeof AiSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/media': {
      id: '/library/media'
      path: '/library/media'
      fullPath: '/library/media'
      preLoaderRoute: typeof LibraryMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-studio/opportunities/$opportunityId/briefing': {
      id: '/professional-studio/opportunities/$opportunityId/briefing'
      path: '/opportunities/$opportunityId/briefing'
      fullPath: '/professional-studio/opportunities/$opportunityId/briefing'
      preLoaderRoute: typeof ProfessionalStudioOpportunitiesOpportunityIdBriefingRouteImport
      parentRoute: typeof ProfessionalStudioRoute
    }
    '/library/books/$bookId/read': {
      id: '/library/books/$bookId/read'
      path: '/library/books/$bookId/read'
      fullPath: '/library/books/$bookId/read'
      preLoaderRoute: typeof LibraryBooksBookIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfessionalStudioRouteChildren {
  ProfessionalStudioOpportunitiesOpportunityIdBriefingRoute: typeof ProfessionalStudioOpportunitiesOpportunityIdBriefingRoute
}

const ProfessionalStudioRouteChildren: ProfessionalStudioRouteChildren = {
  ProfessionalStudioOpportunitiesOpportunityIdBriefingRoute:
    ProfessionalStudioOpportunitiesOpportunityIdBriefingRoute,
}

const ProfessionalStudioRouteWithChildren =
  ProfessionalStudioRoute._addFileChildren(ProfessionalStudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AiSalesRoute: AiSalesRoute,
  CommunityRoute: CommunityRoute,
  ConhecaSenseyRoute: ConhecaSenseyRoute,
  ContentStudioRoute: ContentStudioRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  ProfessionalStudioRoute: ProfessionalStudioRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoreRoute: StoreRoute,
  WorkspaceRoute: WorkspaceRoute,
  LibraryMediaRoute: LibraryMediaRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryBooksBookIdReadRoute: LibraryBooksBookIdReadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
