# Generated by Django 6.0 for PPS 1.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source", models.CharField(choices=[("99FREELAS", "99Freelas"), ("WORKANA", "Workana"), ("UPWORK", "Upwork"), ("DIRECT_CLIENT", "Cliente direto"), ("REFERRAL", "Indicação"), ("PROSPECTING", "Prospecção"), ("AGENCIA_3DS", "Agência 3DS"), ("OWN_PROJECT", "Projeto próprio"), ("OTHER", "Outra")], max_length=20)),
                ("source_url", models.URLField(blank=True)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("client_reference", models.CharField(blank=True, max_length=255)),
                ("budget_min", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("budget_max", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(default="BRL", max_length=3)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("proposal_deadline", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("NEW", "Nova"), ("ANALYZING", "Em análise"), ("INTERESTED", "Interessado"), ("NEGOTIATING", "Negociando"), ("PROPOSAL_SENT", "Proposta enviada"), ("WON", "Ganha"), ("LOST", "Perdida"), ("REJECTED", "Rejeitada"), ("ARCHIVED", "Arquivada")], default="NEW", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="professional_opportunities", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="opportunity", index=models.Index(fields=["created_by", "-created_at"], name="opp_owner_created_idx")),
    ]

