# Generated by Django 6.0.6 on 2026-09-01 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_opportunitybriefing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('GO', 'Go'), ('CAUTION', 'Caution'), ('NO_GO', 'No-go')], max_length=10)),
                ('score', models.PositiveSmallIntegerField()),
                ('problem_summary', models.TextField()),
                ('client_need', models.TextField()),
                ('likely_deliverables', models.JSONField(default=list)),
                ('technologies', models.JSONField(default=list)),
                ('required_competencies', models.JSONField(default=list)),
                ('complexity', models.CharField(max_length=30)),
                ('technical_risks', models.JSONField(default=list)),
                ('commercial_risks', models.JSONField(default=list)),
                ('ambiguities', models.JSONField(default=list)),
                ('missing_information', models.JSONField(default=list)),
                ('client_questions', models.JSONField(default=list)),
                ('external_dependencies', models.JSONField(default=list)),
                ('estimated_deadline', models.TextField()),
                ('estimated_effort', models.JSONField(default=dict)),
                ('ai_execution_fit', models.TextField()),
                ('competency_gap', models.JSONField(default=dict)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('pricing', models.JSONField(default=dict)),
                ('limitations', models.JSONField(default=list)),
                ('ai_provider', models.CharField(max_length=80)),
                ('ai_model', models.CharField(blank=True, max_length=120)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_analyses', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viability_analysis', to='professional.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityExecutionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=300)),
                ('phases', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('validation', models.JSONField(default=list)),
                ('delivery', models.JSONField(default=list)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('ai_provider', models.CharField(max_length=80)),
                ('ai_model', models.CharField(blank=True, max_length=120)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_execution_plans', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_plan', to='professional.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('SHORT', 'Curta'), ('CONSULTATIVE', 'Consultiva'), ('TECHNICAL', 'Técnica')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('APPROVED', 'Aprovada')], default='DRAFT', max_length=10)),
                ('greeting', models.TextField()),
                ('understanding', models.TextField()),
                ('approach', models.TextField()),
                ('deliverables', models.JSONField(default=list)),
                ('deadline', models.TextField()),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('essential_questions', models.JSONField(default=list)),
                ('differentiators', models.JSONField(default=list)),
                ('closing', models.TextField()),
                ('ai_provider', models.CharField(max_length=80)),
                ('ai_model', models.CharField(blank=True, max_length=120)),
                ('generation_version', models.CharField(default='v1', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_proposals', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='professional.opportunity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'version'), name='unique_opportunity_proposal_version')],
            },
        ),
    ]
