# Generated by Django 6.0.6 on 2026-09-07 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_opportunityanalysis_opportunityexecutionplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityExecutionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('CODE', 'Código'), ('TEST', 'Teste'), ('ARCHITECTURE', 'Arquitetura'), ('TECHNICAL_DECISION', 'Decisão técnica'), ('DEBUGGING', 'Debugging'), ('DOCUMENTATION', 'Documentação'), ('DELIVERABLE', 'Entregável'), ('OTHER', 'Outro')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True)),
                ('confidentiality', models.CharField(choices=[('PRIVATE', 'Privado'), ('ANONYMIZED', 'Pode ser usado de forma anonimizada'), ('SHAREABLE', 'Pode ser compartilhado')], db_index=True, default='PRIVATE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_execution_artifacts', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_artifacts', to='professional.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opportunity', '-created_at'], name='exec_artifact_opp_idx')],
            },
        ),
    ]
