import { useEffect, useState } from "react";
import { AxiosError } from "axios";
import { Download, ExternalLink, LoaderCircle, Pencil, Printer, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Textarea } from "@/components/ui/textarea";
import { api } from "@/lib/api";
export type IntelligentBriefing={id:number;opportunity:number;problem:string;objective:string;target_audience:string;deliverables:string[];functional_requirements:string[];non_functional_requirements:string[];integrations:string[];data_requirements:string[];infrastructure_requirements:string[];constraints:string[];dependencies:string[];assumptions:string[];scope_risks:string[];ambiguities:string[];client_questions:string[];acceptance_criteria:string[];ai_provider:string;ai_model:string;updated_at:string};
const textFields=[["problem","Problema"],["objective","Objetivo"],["target_audience","Público-alvo"]] as const;
type ListKey="deliverables"|"functional_requirements"|"non_functional_requirements"|"integrations"|"data_requirements"|"infrastructure_requirements"|"constraints"|"dependencies"|"assumptions"|"scope_risks"|"ambiguities"|"client_questions"|"acceptance_criteria";
type ListField=readonly [ListKey,string];
const groups:readonly (readonly [string,string,readonly ListField[]])[]=[["scope","Escopo e entrega",[["deliverables","Entregáveis"],["functional_requirements","Requisitos funcionais"],["acceptance_criteria","Critérios de aceite"]]],["architecture","Arquitetura e operação",[["non_functional_requirements","Requisitos não funcionais"],["integrations","Integrações"],["data_requirements","Dados necessários"],["infrastructure_requirements","Infraestrutura"]]],["risks","Riscos e validações",[["constraints","Restrições"],["dependencies","Dependências"],["assumptions","Premissas"],["scope_risks","Riscos de escopo"],["ambiguities","Ambiguidades"],["client_questions","Perguntas para o cliente"]]]];
const listFields:ListField[]=groups.flatMap(group=>[...group[2]]);
function safeMessage(error:unknown){return error instanceof AxiosError&&typeof error.response?.data?.detail==="string"?error.response.data.detail:"Não foi possível concluir a operação."}
export function IntelligentBriefingPanel({opportunityId,standalone=false}:{opportunityId:number;standalone?:boolean}){
 const [briefing,setBriefing]=useState<IntelligentBriefing|null>(null),[draft,setDraft]=useState<IntelligentBriefing|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[exporting,setExporting]=useState<string|null>(null),[error,setError]=useState(""),[actionError,setActionError]=useState("");
 async function load(){setLoading(true);setError("");try{setBriefing((await api.get<IntelligentBriefing>(`/api/professional/opportunities/${opportunityId}/briefing/`)).data)}catch(e){if(e instanceof AxiosError&&e.response?.status===404)setBriefing(null);else setError("Não foi possível carregar o briefing inteligente.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[opportunityId]);
 async function generate(replace=false){if(replace&&!window.confirm("Gerar novamente substituirá o briefing atual. Continuar?"))return;setBusy(true);setActionError("");try{setBriefing((await api.post<IntelligentBriefing>(`/api/professional/opportunities/${opportunityId}/generate-briefing/`,{})).data);setDraft(null);toast.success("Briefing inteligente gerado.")}catch(e){const message=safeMessage(e);setActionError(message);toast.error(message)}finally{setBusy(false)}}
 async function save(){if(!draft)return;setBusy(true);try{const payload=Object.fromEntries([...textFields,...listFields].map(([field])=>[field,draft[field]]));setBriefing((await api.patch<IntelligentBriefing>(`/api/professional/opportunities/${opportunityId}/briefing/`,payload)).data);setDraft(null);toast.success("Briefing revisado e salvo.")}catch(e){toast.error(safeMessage(e))}finally{setBusy(false)}}
 async function download(format:string){setExporting(format);try{const response=await api.get(`/api/professional/opportunities/${opportunityId}/briefing/export/${format}/`,{responseType:"blob"});const url=URL.createObjectURL(response.data);const a=document.createElement("a");a.href=url;a.download=`briefing.${format}`;a.click();URL.revokeObjectURL(url);toast.success(`Exportação ${format.toUpperCase()} concluída.`)}catch(e){toast.error(safeMessage(e))}finally{setExporting(null)}}
 return <section className={`${standalone?"briefing-print-area":"mt-2 sm:col-span-2"} rounded-xl border bg-card p-5`} aria-label="Briefing inteligente"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-xs font-bold uppercase tracking-[.18em] text-kaizen">Professional Project Studio</p><h2 className="mt-1 text-2xl font-black">Briefing Inteligente</h2></div>{briefing&&!draft&&<div className="no-print flex flex-wrap gap-2">{!standalone&&<Button size="sm" variant="outline" onClick={()=>window.open(`/professional-studio/opportunities/${opportunityId}/briefing`,"_blank","noopener,noreferrer")}><ExternalLink/>Abrir briefing</Button>}<Button size="sm" variant="outline" onClick={()=>setDraft(structuredClone(briefing))}><Pencil/>Editar briefing</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void generate(true)}><Sparkles/>Gerar novamente</Button><Button size="sm" variant="outline" onClick={()=>standalone?window.print():window.open(`/professional-studio/opportunities/${opportunityId}/briefing?print=1`,"_blank","noopener,noreferrer")}><Printer/>Imprimir</Button><DropdownMenu><DropdownMenuTrigger asChild><Button size="sm" disabled={!!exporting}>{exporting?<LoaderCircle className="animate-spin"/>:<Download/>}Exportar</Button></DropdownMenuTrigger><DropdownMenuContent>{["pdf","docx","pptx","md","json"].map(f=><DropdownMenuItem key={f} onClick={()=>void download(f)}>{f.toUpperCase()}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div>}</div>{actionError&&<p className="mt-4 text-sm text-destructive" role="alert">{actionError}</p>}
 {loading?<p className="mt-6 text-sm text-muted-foreground">Carregando briefing...</p>:error?<p className="mt-6 text-sm text-destructive">{error}</p>:!briefing?<div className="mt-6 rounded-lg border border-dashed p-6 text-center"><p>Nenhum briefing inteligente foi gerado.</p><Button className="no-print mt-3" disabled={busy} onClick={()=>void generate()}><Sparkles/>Gerar briefing com IA</Button></div>:draft?<div className="mt-6 grid gap-4 sm:grid-cols-2">{[...textFields,...listFields].map(([field,label])=><label key={field} className="space-y-1"><span className="text-xs font-bold">{label}</span><Textarea rows={4} value={Array.isArray(draft[field])?(draft[field] as string[]).join("\n"):draft[field] as string} onChange={e=>setDraft(current=>current?{...current,[field]:Array.isArray(current[field])?e.target.value.split("\n").map(x=>x.trim()).filter(Boolean):e.target.value}:current)}/></label>)}<div className="no-print flex gap-2 sm:col-span-2"><Button disabled={busy} onClick={()=>void save()}>Salvar briefing</Button><Button variant="outline" onClick={()=>setDraft(null)}>Cancelar</Button></div></div>:<BriefingReader briefing={briefing}/>}</section>
}
function BriefingReader({briefing}:{briefing:IntelligentBriefing}){return <article className="mt-6"><section className="rounded-xl border border-kaizen/25 bg-kaizen/5 p-5"><h3 className="text-sm font-black uppercase tracking-wide">Resumo executivo</h3><div className="mt-4 grid gap-5 md:grid-cols-3">{textFields.map(([field,label])=><Field key={field} label={label} values={briefing[field]?[briefing[field]]:[]}/>)}</div></section><Accordion type="multiple" defaultValue={groups.map(g=>g[0])} className="mt-5">{groups.map(([id,title,fields])=><AccordionItem key={id} value={id}><AccordionTrigger className="text-base font-bold">{title}</AccordionTrigger><AccordionContent><div className="grid gap-5 pb-2 md:grid-cols-2">{fields.map(([field,label])=><Field key={field} label={label} values={briefing[field]}/>)}</div></AccordionContent></AccordionItem>)}</Accordion><p className="mt-5 text-[11px] text-muted-foreground">Gerado por {briefing.ai_provider}{briefing.ai_model?` · ${briefing.ai_model}`:""}. Atualizado em {new Date(briefing.updated_at).toLocaleString("pt-BR")}.</p></article>}
function Field({label,values}:{label:string;values:string[]}){return <div><h4 className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</h4>{values.length?<ul className="mt-2 space-y-2 text-sm">{values.map((value,index)=><li key={index} className="flex gap-2"><span className="text-kaizen">•</span><span>{value}</span></li>)}</ul>:<p className="mt-2 text-sm italic text-muted-foreground">Não informado.</p>}</div>}
