import { useEffect, useState } from "react";
import { AxiosError } from "axios";
import { Check, Clipboard, LoaderCircle, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { api } from "@/lib/api";

type Version="SHORT"|"CONSULTATIVE"|"TECHNICAL";
type Analysis={decision:"GO"|"CAUTION"|"NO_GO";score:number;problem_summary:string;client_need:string;likely_deliverables:string[];technical_risks:string[];commercial_risks:string[];ambiguities:string[];client_questions:string[];competency_gap:Record<string,string[]>;score_breakdown:Record<string,number>;estimated_effort:Record<string,string|string[]>;pricing:{insufficient_data:boolean;suggested_range:string;minimum_recommended:string;target:string;justification:string;change_factors:string[]};limitations:string[];ai_provider:string;ai_model:string;generated_at:string};
type Proposal={id:number;version:Version;status:"DRAFT"|"APPROVED";greeting:string;understanding:string;approach:string;deliverables:string[];deadline:string;suggested_price:string|null;currency:string;essential_questions:string[];differentiators:string[];closing:string;approved_at:string|null};
type Plan={project:string;phases:{name:string;acceptance_criteria:string[];tasks:{objective:string;description:string;expected_result:string;validation:string;ai_help:string;human_validation:string}[]}[];risks:string[];validation:string[];delivery:string[];status:string};

function safeMessage(error:unknown){return error instanceof AxiosError&&typeof error.response?.data?.detail==="string"?error.response.data.detail:"Não foi possível concluir a operação."}
const labels:Record<Version,string>={SHORT:"Curta",CONSULTATIVE:"Consultiva",TECHNICAL:"Técnica"};

export function MoneyWorkflowPanel({opportunityId}:{opportunityId:number}){
 const [analysis,setAnalysis]=useState<Analysis|null>(null),[proposal,setProposal]=useState<Proposal|null>(null),[plan,setPlan]=useState<Plan|null>(null);
 const [version,setVersion]=useState<Version>("CONSULTATIVE"),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const [draft,setDraft]=useState<Proposal|null>(null);
 async function loadAnalysis(){try{const response=await api.get<Analysis>(`/api/professional/opportunities/${opportunityId}/analysis/`);setAnalysis(response.data);}catch(error){if(!(error instanceof AxiosError)||error.response?.status!==404)setError("Não foi possível carregar a análise.");}}
 async function loadProposal(selected=version){try{const response=await api.get<Proposal>(`/api/professional/opportunities/${opportunityId}/proposal/`,{params:{version:selected}});setProposal(response.data);setDraft(response.data);}catch(error){if(error instanceof AxiosError&&error.response?.status===404){setProposal(null);setDraft(null);}else setError("Não foi possível carregar a proposta.");}}
 async function loadPlan(){try{const response=await api.get<Plan>(`/api/professional/opportunities/${opportunityId}/execution-plan/`);setPlan(response.data);}catch(error){if(!(error instanceof AxiosError)||error.response?.status!==404)setError("Não foi possível carregar o plano.");}}
 useEffect(()=>{setError("");void Promise.all([loadAnalysis(),loadProposal(version),loadPlan()]);},[opportunityId]);
 async function run(key:string,action:()=>Promise<void>){setBusy(key);setError("");try{await action();}catch(error){const detail=safeMessage(error);setError(detail);toast.error(detail);}finally{setBusy("");}}
 async function analyze(){await run("analysis",async()=>{const response=await api.post<Analysis>(`/api/professional/opportunities/${opportunityId}/analyze/`,{});setAnalysis(response.data);toast.success("Análise de viabilidade concluída.");});}
 async function changeVersion(next:Version){setVersion(next);setProposal(null);setDraft(null);await loadProposal(next);}
 async function generateProposal(){await run("proposal",async()=>{const response=await api.post<Proposal>(`/api/professional/opportunities/${opportunityId}/generate-proposal/`,{version});setProposal(response.data);setDraft(response.data);toast.success("Proposta gerada como rascunho.");});}
 async function saveProposal(){if(!draft)return;await run("save",async()=>{const response=await api.patch<Proposal>(`/api/professional/opportunities/${opportunityId}/proposal/`,{version,understanding:draft.understanding,approach:draft.approach,deadline:draft.deadline,suggested_price:draft.suggested_price,currency:draft.currency,closing:draft.closing});setProposal(response.data);setDraft(response.data);toast.success("Revisão humana salva.");});}
 async function approve(){await run("approve",async()=>{const response=await api.post<Proposal>(`/api/professional/opportunities/${opportunityId}/proposal/approve/`,{version});setProposal(response.data);setDraft(response.data);toast.success("Proposta aprovada para cópia.");});}
 async function copy(){if(!proposal||proposal.status!=="APPROVED")return;const text=[proposal.greeting,proposal.understanding,proposal.approach,proposal.deliverables.length?`Entregáveis:\n${proposal.deliverables.map(item=>`- ${item}`).join("\n")}`:"",`Prazo: ${proposal.deadline}`,proposal.suggested_price?`Investimento: ${proposal.currency} ${proposal.suggested_price}`:"",proposal.essential_questions.length?`Perguntas:\n${proposal.essential_questions.map(item=>`- ${item}`).join("\n")}`:"",proposal.closing].filter(Boolean).join("\n\n");await navigator.clipboard.writeText(text);toast.success("Proposta copiada.");}
 async function generatePlan(){await run("plan",async()=>{const response=await api.post<Plan>(`/api/professional/opportunities/${opportunityId}/generate-execution-plan/`,{proposal_version:version});setPlan(response.data);toast.success("Plano inicial gerado.");});}
 const update=(field:keyof Proposal,value:string)=>setDraft(current=>current?{...current,[field]:value}:current);

 return <section className="space-y-5 sm:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">Análise de viabilidade</h3><p className="text-xs text-muted-foreground">Decisão assistida por IA, sempre sujeita à revisão humana.</p></div><Button type="button" onClick={()=>void analyze()} disabled={!!busy}>{busy==="analysis"?<LoaderCircle className="animate-spin"/>:<Sparkles/>}{analysis?"Reanalisar oportunidade":"Analisar oportunidade"}</Button></div>{error&&<p role="alert" className="rounded border border-destructive/40 p-3 text-sm text-destructive">{error}</p>}{analysis&&<div className="rounded-lg border p-4"><div className="flex items-center gap-3"><Badge variant={analysis.decision==="GO"?"default":analysis.decision==="NO_GO"?"destructive":"secondary"}>{analysis.decision}</Badge><strong>Score {analysis.score}/100</strong></div><p className="mt-3">{analysis.problem_summary}</p><p className="mt-2 text-sm text-muted-foreground">{analysis.client_need}</p><Columns title="Riscos" values={[...analysis.technical_risks,...analysis.commercial_risks]}/><Columns title="Perguntas ao cliente" values={analysis.client_questions}/><Columns title="Limitações" values={analysis.limitations}/><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p><b>Esforço provável:</b> {String(analysis.estimated_effort.probable??"Não informado")}</p><p><b>Prazo:</b> {String(analysis.estimated_effort.suggested_deadline??"Não informado")}</p><p><b>Preço-alvo:</b> {analysis.pricing.target||"Dados insuficientes"}</p></div></div>}
 <div className="border-t pt-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-lg font-bold">Proposta comercial</h3><label className="mt-2 block text-xs text-muted-foreground">Versão<select aria-label="Versão da proposta" className="ml-2 rounded border bg-background px-2 py-1" value={version} onChange={event=>void changeVersion(event.target.value as Version)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><Button type="button" variant="outline" onClick={()=>void generateProposal()} disabled={!analysis||!!busy}>{busy==="proposal"?<LoaderCircle className="animate-spin"/>:<Sparkles/>}{proposal?"Regenerar rascunho":"Gerar proposta"}</Button></div>{draft&&<div className="mt-4 space-y-3 rounded-lg border p-4"><div className="flex justify-between"><Badge variant={draft.status==="APPROVED"?"default":"secondary"}>{draft.status}</Badge><span className="text-xs text-muted-foreground">{labels[draft.version]}</span></div><label className="block text-sm font-medium">Entendimento<Textarea className="mt-1" value={draft.understanding} disabled={draft.status==="APPROVED"} onChange={event=>update("understanding",event.target.value)}/></label><label className="block text-sm font-medium">Abordagem<Textarea className="mt-1" value={draft.approach} disabled={draft.status==="APPROVED"} onChange={event=>update("approach",event.target.value)}/></label><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-medium">Prazo<Input value={draft.deadline} disabled={draft.status==="APPROVED"} onChange={event=>update("deadline",event.target.value)}/></label><label className="text-sm font-medium">Preço<Input type="number" min="0" value={draft.suggested_price??""} disabled={draft.status==="APPROVED"} onChange={event=>update("suggested_price",event.target.value)}/></label><label className="text-sm font-medium">Moeda<Input maxLength={3} value={draft.currency} disabled={draft.status==="APPROVED"} onChange={event=>update("currency",event.target.value.toUpperCase())}/></label></div><label className="block text-sm font-medium">Encerramento<Textarea className="mt-1" value={draft.closing} disabled={draft.status==="APPROVED"} onChange={event=>update("closing",event.target.value)}/></label><div className="flex flex-wrap gap-2">{draft.status==="DRAFT"&&<><Button variant="outline" onClick={()=>void saveProposal()} disabled={!!busy}>Salvar edição</Button><Button onClick={()=>void approve()} disabled={!!busy}><Check/>Aprovar proposta</Button></>}<Button variant="outline" onClick={()=>void copy()} disabled={draft.status!=="APPROVED"}><Clipboard/>Copiar proposta</Button></div></div>}</div>
 <div className="border-t pt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">Plano inicial de execução</h3><p className="text-xs text-muted-foreground">Disponível depois da aprovação humana.</p></div><Button variant="outline" onClick={()=>void generatePlan()} disabled={proposal?.status!=="APPROVED"||!!busy}>{busy==="plan"?<LoaderCircle className="animate-spin"/>:<Sparkles/>}Gerar plano inicial</Button></div>{plan&&<div className="mt-4 rounded-lg border p-4"><h4 className="font-bold">{plan.project}</h4>{plan.phases.map((phase,index)=><div key={`${index}-${phase.name}`} className="mt-3"><p className="font-medium">{index+1}. {phase.name}</p><ul className="ml-5 list-disc text-sm text-muted-foreground">{phase.tasks.map((task,item)=><li key={`${item}-${task.objective}`}>{task.objective} — {task.expected_result}</li>)}</ul></div>)}</div>}</div></section>;
}

function Columns({title,values}:{title:string;values:string[]}){if(!values.length)return null;return <div className="mt-3"><b className="text-sm">{title}</b><ul className="ml-5 list-disc text-sm text-muted-foreground">{values.map((value,index)=><li key={`${index}-${value}`}>{value}</li>)}</ul></div>}
